version: "3"
services:
  web:
    build:
      context: .
      dockerfile: DockerfileClient
    volumes:
      - ./client:/app
      - /app/node_modules
    ports:
      - "8081:8081"
    command: "npm start"
    links:
      - server
  server:
    build:
      context: .
      dockerfile: DockerfileServer
    volumes:
      - ./server:/app
      - /app/node_modules
    ports:
      - "3001:3001"
    command: "npm run dev"

      